export enum Methods {
    GET_NETWORK_ID = 'GetNetworkId',
    GET_BLOCKCHAIN_INFO = 'GetBlockchainInfo',
    GET_DS_BLOCK = 'GetDsBlock',
    GET_LATEST_DS_BLOCK = 'GetLatestDsBlock',
    GET_NUM_DS_BLOCKS = 'GetNumDSBlocks',
    GET_DS_BLOCK_RATE = 'GetDSBlockRate',
    DS_BLOCK_LISTING = 'DSBlockListing',
    GET_TX_BLOCK = 'GetTxBlock',
    GETLATESTTXBLOCK = 'GetLatestTxBlock',
    GET_NUM_TX_BLOCKS = 'GetNumTxBlocks',
    GET_TX_BLOCK_RATE = 'GetTxBlockRate',
    TX_BLOCK_LISTING = 'TxBlockListing',
    GET_NUM_TRANSACTIONS = 'GetNumTransactions',
    GET_TRANSACTION_RATE = 'GetTransactionRate',
    GET_CURRENT_MINI_EPOCH = 'GetCurrentMiniEpoch',
    GET_CURRENT_DS_EPOCH = 'GetCurrentDSEpoch',
    GET_PREV_DIFFICULTY = 'GetPrevDifficulty',
    GET_PREV_DS_DIFFICULTY = 'GetPrevDSDifficulty',
    GET_TOTAL_COIN_SUPPLY = 'GetTotalCoinSupply',
    GET_MINER_INFO = 'GetMinerInfo'
}
